name: CI

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

  workflow_dispatch:

jobs:
  activation:
    name: Request manual activation file 🔑
    runs-on: ubuntu-latest

    steps:
      - name: Unity - Activate
        id: getManualLicenseFile
        uses: webbertakken/unity-request-manual-activation-file@v1.1
        with:
          unityVersion: 2020.1.0f1
      - name: Expose as artifact
        uses: actions/upload-artifact@v1
        with:
          name: ${{ steps.getManualLicenseFile.outputs.filePath }}
          path: ${{ steps.getManualLicenseFile.outputs.filePath }}  
